<a href="https://colab.research.google.com/github/himanshu180105/Data_Science/blob/main/pandas_lect06.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
dct = {
    'name': ['Tom','Nick','Krish','Jack'],
    'age':[20,21,22,23],
    'roll':[1,2,3,4]
}


df = pd.DataFrame(dct,index = ['a','b','c','d'])
# to customize or manage index
# df
# print(df)
display(df)

    name  age  roll
a    Tom   20     1
b   Nick   21     2
c  Krish   22     3
d   Jack   23     4

In [50]:
df = pd.read_csv('student_data.csv')
# df.head(3)
# df.tail(3)
# df.info()
# df.shape
# df.describe()
# standard deviation is used find the vary data how much change you will get
# quartiles are the type of median

# df.columns
# df.index
# df[['internet_usage','study_hours']]


# df2 = df.loc[df['study_hours']==11]
# display(df2)

# df3 = df.iloc[4]
# display[df3]

In [54]:
import pandas as pd
df = pd.read_csv('student_data.csv')

df.loc[df['assignments_completed']==8].iloc[1]

study_hours                   5
attendance                   52
sleep_hours                   8
internet_usage                6
assignments_completed         8
previous_score               40
exam_score                78.82
placement_status         Placed
Name: 4, dtype: object

In [102]:
df = pd.read_csv('student_data.csv')
# df[df['assignments_completed'] > 3]

# df["age"] = 20

# rename columns
# df = df.rename(columns = {"assignments_completed": "assign_completed"},inplace = True)

# df.drop(columns =["sleep_hours"], inplace = True)
# df.drop(index=[2],inplace = True)

# df.dropna()
# df.sort_values(4)
# df.sort_index(5)


#  home work
 # how to use lambda function inside sort functions

,study_hours,attendance,sleep_hours,internet_usage,assignments_completed,previous_score,exam_score,placement_status
0,7,56,8,7,10,62,100.00,Placed
1,4,69,5,3,8,56,100.00,Placed
2,11,60,7,6,10,45,100.00,Placed
3,8,99,9,8,4,55,90.17,Placed
4,5,52,8,6,8,40,78.82,Placed
...,...,...,...,...,...,...,...,...
9995,2,58,9,7,8,88,69.31,Not Placed
9996,7,98,6,9,4,87,100.00,Placed
9997,10,44,8,5,10,37,95.94,Placed
9998,10,75,7,5,8,52,88.61,Placed
9999,2,70,6,11,16,52,78.96,Placed

In [108]:
df = pd.read_csv('student_data.csv')

# check for missing values
# df.isnull()

# check for non missing values
# df.notnull()

# replace missing values
# df.fillna()


# find unique values for a series only
df['attendance'].unique()

# df

array([ 56,  69,  60,  99,  52,  40,  86,  72,  77,  64,  65,  98,  67,
        76,  80,  96,  88,  87,  47,  95,  51,  44,  63,  45,  71,  81,
        42,  58,  82,  68,  89,  41,  48,  85,  75, 100,  59,  43,  54,
        55,  50,  94,  93,  73,  61,  90,  66,  49,  97,  70,  84,  74,
        92,  46,  91,  83,  79,  78,  57,  62,  53])