<a href="https://colab.research.google.com/github/himanshu180105/Data_Science/blob/main/pandas_lec07_joint.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('student_data.csv')

In [3]:
df.groupby('placement_status')['placement_status'].agg('count')

placement_status
Not Placed    1644
Placed        8356
Name: placement_status, dtype: int64

In [9]:
df.groupby('placement_status')['exam_score'].agg('std')

placement_status
Not Placed    8.147050
Placed        9.377072
Name: exam_score, dtype: float64

In [11]:
df.groupby('placement_status')['study_hours'].agg('mean')

placement_status
Not Placed    3.130170
Placed        6.552178
Name: study_hours, dtype: float64

In [13]:
df.groupby('study_hours')['exam_score'].agg('mean')

study_hours
1     71.264562
2     75.169142
3     78.974939
4     81.845483
5     84.964142
6     88.620043
7     90.539568
8     93.297697
9     95.462126
10    96.574628
11    97.303283
Name: exam_score, dtype: float64

In [14]:
df.groupby('exam_score')['study_hours'].agg('mean')

exam_score
26.67     1.000000
26.89     1.000000
27.82     1.000000
31.41     1.000000
31.43     2.000000
            ...
99.96     7.000000
99.97     7.000000
99.98     7.000000
99.99     6.666667
100.00    8.078977
Name: study_hours, Length: 3563, dtype: float64

In [1]:
# df['grade']=df['exam_score'].apply(lambda x: 'A' if x>=90 else ('B' if x>=80 else ('C' if x>=70 else ('D' if x>=60 else 'E'))))

def grades(score):
  if score >= 90:
    return 'A'
  elif score >= 80:
    return 'B'
  elif score >= 70:
    return 'C'
  elif score >= 60:
    return 'D'
  else:
    return 'F'

    df['grade']=df['exam_score'].apply(grades)
    df